### ISSUE TITLE
pytorch profiler tensorboard plugin not showing cuda activities - torch - 1.13

### ISSUE THREAD

**Issue by shrinath-suresh** [pytorch/kineto#679]
While trying to profile runs with and without functorch, we observed that the pytorch profiler is not showing up the cuda activities in tensorboard UI..

Required pip packages

```
torch==1.13.0
transformers==4.24.0
torch-tb-profiler==0.4.0
timeit
tqdm
```

Script to reproduce

bert_vmap.py
```
import timeit

import torch
from functorch import combine_state_for_ensemble, vmap
from tqdm import tqdm
from transformers import BertTokenizer, BertModel


def load_model():
    tokenizer = BertTokenizer.from_pretrained("bert-base-cased")
    model = BertModel.from_pretrained("bert-base-cased")
    return model, tokenizer


def run_sample_prediction(model, tokenizer, encoded_input):
    output = model(**encoded_input)
    print(output.last_hidden_state)
    print(output.last_hidden_state.shape)


def serve_multiple_models(model, tokenizer, encoded_input):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    NUM_OF_MODELS = 5
    models = [model.to(device) for _ in range(NUM_OF_MODELS)]

    encoded_input = tokenizer(text, return_tensors="pt")
    encoded_input = encoded_input.to(device)

    print("Running Warm up")
    WARM_UP = 10
    for _ in tqdm(range(WARM_UP)):
        _ = [model(**encoded_input, return_dict=False) for model in models]

    profiler_args = {
        "activities": [
            torch.profiler.ProfilerActivity.CPU,
            torch.profiler.ProfilerActivity.CUDA,
        ],
        "on_trace_ready": torch.profiler.tensorboard_trace_handler("./without_vmap"),
        "record_shapes": True
    }

    N_REPEAT = 100
    mean_hf_time = 0
    with torch.profiler.profile(**profiler_args) as prof:
        for _ in tqdm(range(N_REPEAT)):
            mean_hf_time += timeit.timeit(
                lambda: [model(**encoded_input, return_dict=False) for model in models], number=1
            )
    prof.step()
    print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10))

    print("Avg time taken for prediction without vmap: ", round(mean_hf_time / N_REPEAT, 2))
    print("\n")

    fmodel, params, buffers = combine_state_for_ensemble(models)
    [p.requires_grad_() for p in params]

    print("Running Warm up")
    WARM_UP = 10
    for _ in tqdm(range(WARM_UP)):
        _ = vmap(fmodel)(params, buffers, **encoded_input, return_dict=False)

    N_REPEAT = 100
    mean_hf_time = 0
    
    profiler_args = {
        "activities": [
            torch.profiler.ProfilerActivity.CPU,
            torch.profiler.ProfilerActivity.CUDA,
        ],
        "on_trace_ready": torch.profiler.tensorboard_trace_handler("./with_vmap"),
        "record_shapes": True
    }
    with torch.profiler.profile(**profiler_args) as prof:
        for _ in tqdm(range(N_REPEAT)):
            mean_hf_time += timeit.timeit(
                lambda: vmap(fmodel)(params, buffers, **encoded_input, return_dict=False), number=1
            )
    prof.step()
    print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10))

    print("Avg time taken for prediction with vmap: ", round(mean_hf_time / N_REPEAT, 2))


if __name__ == "__main__":
    model, tokenizer = load_model()
    text = "bloomberg has reported on the economy"
    encoded_input = tokenizer(text, return_tensors="pt")

    print("\n Running Sample prediction")

    run_sample_prediction(model=model, tokenizer=tokenizer, encoded_input=encoded_input)
    print("\n")

    serve_multiple_models(model=model, tokenizer=tokenizer, encoded_input=encoded_input)
```

Attaching the logs where cuda activity statistics are printed.

[bert_vmap_log.txt](https://github.com/pytorch/kineto/files/9957772/bert_vmap_log.txt)

Run the following command 
```
mkdir logs
mv with_vmap logs/with_vmap
mv without_vmap logs
tensorboard --logdir logs --bind_all
```
Attaching screenshots of profiler 
![image](https://user-images.githubusercontent.com/63862647/200479972-5f35d94c-40e4-421e-b6fa-63818cc236b4.png)
![image](https://user-images.githubusercontent.com/63862647/200480019-009755e0-8cae-45d6-9d03-14956089c564.png)
![image](https://user-images.githubusercontent.com/63862647/200480312-36d8deae-da88-4479-bff2-bb50afb251e1.png)

In the Overview section, device type is shown as CPU. CUDA events are missing.

**Comment by shrinath-suresh** [comment]
Ran the same test with `pytorch==1.12.1`. I am able to view GPU stats in overview page

[pt12_bert.zip](https://github.com/pytorch/kineto/files/9957859/pt12_bert.zip)

unzip and run
`python pt12_bert.py`

![image](https://user-images.githubusercontent.com/63862647/200481268-4d3ffe88-9e69-4f00-81e3-ca8ae2c39794.png)

**Comment by K-J-Q** [comment]
Ran the test with 1.12.1+cu113 (windows 10, Quadro RTX 3000)

I encountered the same issue as @shrinath-suresh 

![Screenshot 2022-11-08 134058](https://user-images.githubusercontent.com/71882072/200484228-5bc3af19-9fcf-42da-9246-ab920b26e1f6.png)
4-4081-9781-4ac30a4d3eb0.png)

**Comment by K-J-Q** [comment]
Same issue, but unable to show CUDA with torch==1.12.1
-running Windows 10 (RTX3000)

![image](https://user-images.githubusercontent.com/71882072/200488827-ce024fef-3717-410f-88e5-5896f581a756.png)

**Comment by juanigp** [comment]
Maybe it is related to [#659 ]

**Comment by guotuofeng** [comment]
for windows, the profile doesn't support cupti. For linux, it would be better the trace json file could be shared.

**Comment by shrinath-suresh** [comment]
@guotuofeng 

Attaching the profiler trace files and logs

[logs.zip](https://github.com/pytorch/kineto/files/10150101/logs.zip)
[vmap.txt](https://github.com/pytorch/kineto/files/10150105/vmap.txt)

**Comment by guotuofeng** [comment]
yes, as @juanigp mentioned, it is related to the eventtype case-sensitive issue.

Besides the kernel case issue, it seems the runtime node is changed to "cuda_runtime". The profiler parse code need to be updated to reflect the changes.

**Comment by TheExGenesis** [comment]
facing the same issue in Ubuntu, Python 1.14 , no GPU summary or figures even though it's recognized as a device
![image](https://user-images.githubusercontent.com/7385326/207981937-139f8f38-2bb2-4afc-a008-f7292f695cac.png)

**Comment by shrinath-suresh** [comment]
Looks like, a new release is needed for torch-tb-profiler. I couldnt reproduce the issue when compiling it from source.

**Comment by aaronenyeshi** [comment]
Hi, this issue is fixed in the latest version of tensorboard plugin. It looks like the latest version of tb-plugin was not picked up in PyTorch 1.13 and 1.14. I've reported this issue as well in https://github.com/pytorch/kineto/issues/675.

@chauhang - do you know how we can release the new package of tensorboard? I seems a lot of new issues coming in are related to outdated tb-plugin package.

**Comment by aaronenyeshi** [comment]
A new torch-tb-profiler v0.4.1 has been released. This issue should be fixed there, please take a look: https://pypi.org/project/torch-tb-profiler/0.4.1

**Comment by shrinath-suresh** [comment]
Tested with `torch-tb-profiler==0.4.1` and gpu summary is getting shown.

![image](https://user-images.githubusercontent.com/63862647/210610911-c257f482-a36f-4b52-a11f-460afbfdf525.png)

**Comment by qideng7** [comment]
with torch-tb-profiler = 0.4.1, tensorboard = 2.13.0:
still missing GPU summary in "Overview", 
![image](https://github.com/pytorch/kineto/assets/35273269/64f8b49e-8cb2-4fa5-93a8-019cf1793911)

but available in "Memory"
![image](https://github.com/pytorch/kineto/assets/35273269/a97f1778-f16e-4057-a7f9-d1e049061fa8)

**Comment by Geremia** [comment]
@qideng7  I get this issue, too, with
```
Package                 Version
----------------------- -------
absl-py                 2.1.0
pandas                  2.2.2
tensorboard             2.16.2
tensorboard-data-server 0.7.2
torch-tb-profiler       0.4.3
```
and Pytorch 2.3.1.
